### ISSUE TITLE
组件使用时报错

### ISSUE THREAD

**Issue by crazy-forg** [apicloudcom/act#3]
按照文档说明将act文件夹复制到自己的项目中后, 在页面引入search组件 , 真机预览时报错 :
build finish: total-2, ok-2, err-0
06-17 15:15:48.723 27176 27176 W app3c   : Could not set arguments on input (Reason: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference) at main.js : 0
[2021-6-17 15:15:48][WARN] Could not set arguments on input (Reason: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference) at main.js : 0

**Comment by crazy-forg** [comment]
![image](https://user-images.githubusercontent.com/48788876/122357266-2a77e580-cf86-11eb-9ea0-3f64caf3f4bc.png)
这是相关代码

**Comment by YangYongAn** [comment]
我这里使用以下代码片段测试没有问题:

```js
import ASearch from '../../components/act/a-search';
<a-search $value="val" placeholder="输出" shape="round" background="red"/>
```
![image](https://user-images.githubusercontent.com/4987317/122515779-83a44f80-d040-11eb-93db-bd573b4a068e.png)

请确认你的开发工具版本和页面位置是否正确。
