### ISSUE TITLE
act a-popup  安卓  同一界面 多个a-popup只能弹出第一个pop-up

### ISSUE THREAD

**Issue by unaowan** [apicloudcom/act#8]
示例代码
<template>
  <view class="page">
    <a-nav-bar title="simple-popup" left-arrow/>
    <scroll-view style="flex: 1;" scroll-y>
      <view class="simple">
        <a-cell-group round>
          <a-cell is-link @click="showPopup(0)">展示弹出层1</a-cell>
        </a-cell-group>
      </view>
      <view class="simple">
        <a-cell-group round>
          <a-cell is-link @click="showPopup(1)">展示弹出层2</a-cell>
        </a-cell-group>
      </view>
    </scroll-view>
    <a-popup $show="show[0]">
      <text class="demo-content" @click="test"> 内容1</text>
    </a-popup>
    <a-popup $show="show[1]" :position="position" style="height: 30%;">
      <text class="demo-content">内容2</text>
    </a-popup>

  </view>
</template>

<script>
import ANavBar from "../components/act/a-nav-bar";
import ACell from "../components/act/a-cell";
import ACellGroup from "../components/act/a-cell-group";
import APopup from "../components/act/a-popup";

export default {
  name: "simple-popup",
  components: {APopup, ACellGroup, ACell, ANavBar},
  data() {
    return {
      show: Array.from({length: 10}).fill(false),
      position: ''
    }
  },
  methods: {
    showPopup(index, position) {
      this.data.position = position;
      this.data.show[index] = true;
    },
    myClose(e) {
      console.log('myClose', JSON.stringify(e))
    },
    test() {
      return api.toast({
        msg: "测试点击"
      })
    }
  }
}
</script>
<style scoped>
.page {
  height: 100%;
  flex: 1;
  background-color: #F8F8F8;
}.simple {
  padding-bottom: 28px;
}.simple-title {
  margin: 16px;
  font-weight: 600;
  font-size: 18px;
}
.simple-desc {
  color: #999;
  font-size: 14px;
  margin: 0 16px 16px;
}
.demo-content {
  align-self: center;
  padding: 30px 50px;
}
</style>

**Comment by unaowan** [comment]
act a-popup  安卓  同一界面 多个a-popup只能弹出第一个pop-up
https://developer.yonyou.com/forum.php?mod=viewthread&tid=211909&fromuid=927660
(出处: YonBIP开发者社区)

**Comment by YangYongAn** [comment]
已修复，请查看commit ：https://github.com/apicloudcom/act/commit/2f35c0fbe94a2e05e548323dc28801810fa9d632
